<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_J</name>
   <tag></tag>
   <elementGuidId>c1471eeb-98de-4eb9-b7b3-91aac1d7d500</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bindFaculty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bindFaculty</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>James  AndersonWilliam L. Ford Professor of Marketing and Wholesale DistributionEric T. AndersonHartmarx Professor of Marketing; Director of the Center for Global Marketing PracticeUlf  BockenholtJohn D. Gray Professor of MarketingGalen  BodenhausenLawyer Taylor Professor of Psychology and Marketing, Weinberg College of Arts &amp; Sciences; Professor of Marketing, Kellogg School of Management; Co-Director of the Center on the Science of DiversityGregory  CarpenterJames Farley/Booz Allen Hamilton Professor of Marketing Strategy; Director of the Center for Market Leadership; Faculty Director, Kellogg Markets and Customers Initiative (KMCI)Moran  CerfAssociate Professor of MarketingAlexander  ChernevProfessor of MarketingAnne  CoughlanPolk Bros. Chair in Retailing; Professor of MarketingJennifer  CutlerAssociate Professor of MarketingPing  DongDonald P. Jacobs Scholar; Assistant Professor of MarketingBrett  GordonAssociate Professor of MarketingKent  GraysonAssociate Professor of Marketing; Bernice and Leonard Lavin ProfessorshipLakshman  KrishnamurthiA. Montgomery Ward Professor of MarketingAparna  LabrooProfessor of MarketingAngela Y. LeeMechthild Esser Nemmers Professor of Marketing;Blake  McShaneAssociate Professor of MarketingNeal  RoeseSC Johnson Chair in Global Marketing; Professor of Marketing; Professor of Psychology, Weinberg College of Arts &amp; Sciences (Courtesy)Derek D. RuckerSandy &amp; Morton Goldman Professor of Entrepreneurial Studies in Marketing; Professor of Marketing; Co-chair of Faculty ResearchArtem  TimoshenkoAssistant Professor of MarketingRima  Toure-TilleryAssociate Professor of MarketingAnna  TuchmanAssistant Professor of MarketingAlice M. TyboutHarold T. Martin Professor of MarketingFlorian  ZettelmeyerNancy L. Ertle Professor of Marketing; Faculty Director, Program on Data Analytics at Kellogg; Chair of Marketing DepartmentTimothy  CalkinsClinical Professor of MarketingJulie  HennessyClinical Professor of Marketing; Associate Chair of the Marketing DepartmentJim  LecinskiClincal Associate Professor of Marketing (Courtesy)Michal  MaimaranClinical Associate Professor of Marketing; Research Associate Professor of MarketingKevin  McTigueClinical Associate Professor of MarketingThomas  O'TooleExecutive Director, Program for Data Analytics at Kellogg; Clinical Professor of MarketingMary O'Brien PearlmanClinical Associate Professor of MarketingMohanbir  SawhneyMcCormick Foundation Chair of Technology; Clinical Professor of Marketing; Director of the Center for Research in Technology &amp; Innovation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bindFaculty&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='bindFaculty']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[3]/div/div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenure-line faculty are listed first and clinical second.'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::div[16]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[3]/div/div[3]/div/div[6]</value>
   </webElementXpaths>
</WebElementEntity>
